### ISSUE TITLE
Thymeleaf work

### ISSUE THREAD

**Issue by coskundeniz89** [coskundeniz89/spring-boot-work#3]
@er-han  thymeleaf work projesine örnek thymeleaf partları ekleyebilir misin?

1- list
2- get
3- post with validation
4- if-else
5- fragment 
6- Multi-language

**Comment by er-han** [comment]
@coskundeniz89 yeni bir branchta çalışıyorum zaten bununla ilgili, eklerim eksikleri

**Comment by coskundeniz89** [comment]
Tamamdır

**Comment by coskundeniz89** [comment]
Eyv.
